services:
  - type: web
    name: watchtower
    runtime: python
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: CARGO_HOME
        value: /opt/render/project/src/.cargo
    disk:
      name: watchtower-data
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
